Add controllers
Soylf/java-shareit pull request #1
Opened 2024-01-29 17:32 UTC by Soylf

2024-01-30 06:42 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/error/RestExceptionHandler.java
> +        return new ResponseEntity<>(error, HttpStatus.NOT_FOUND);
Статус можно задать аннотацией на метод `@ResponseStatus(HttpStatus.NOT_FOUND)`
И возвращать  ApiError.
Джава типизированный язык, а сигнатура ResponseEntity<Object> нивелирует типизацию.
Пример 
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ApiError handleNotFoundException(final NotFoundException e) {
		log.info("404 {}", e.getMessage());
		return newApiError(e.getMessage());
	}
```

2024-01-30 06:45 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Optional<ItemDto> getItem(@PathVariable("itemId") Long itemId) {
В контроллерах не принято возвращать Optional. Как Optional будет выглядеть в виде JSON?

2024-01-30 06:47 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +@Service
На интерфейсе аннотация не нужна. Только на тех типах, объекты которых непосредственно будут создаваться спрингом, т.е. на бинах.

2024-01-30 06:49 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (!userDto.getEmail().contains("@")) {
Лучше воспользоваться вадидацией полей с помощью аннотаций.

2024-01-30 06:51 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (users.containsKey(id)) {
Проверять наличие по containsKey нет смысла. Сразу вызываем get, если нет в мапе то вернется null.
Итого одно обращение к мапе против двух

2024-01-30 07:03 UTC, VadimZharkov requested changes
Можно улучшить

2024-01-30 20:29 UTC, Soylf commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (!userDto.getEmail().contains("@")) {
Я и хотел изначально, но чет пошло не так и я забыл, ну и вот почему то у меня анотации с lambok не робят

2024-01-31 06:36 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotEmpty(message = "Неверное название")
Обе эти аннотации можно заменить одной `@NotBlank`
https://ru.stackoverflow.com/questions/804707/%D0%9A%D0%B0%D0%BA%D0%B8%D0%B5-%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B8%D1%8F-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-notempty-notblank-%D0%B8-notnull

2024-01-31 06:43 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (users.containsKey(id)) {
Повторюсь что можно одним обращением к мапе обойтись без containsKey
```
User existingUser = users.get(id);
if (existingUser != null) {
   ...
}
```

2024-01-31 06:45 UTC, VadimZharkov requested changes
Можно еще улучшить

2024-01-31 11:22 UTC, VadimZharkov approved these changes

2024-02-02 07:40 UTC, merged