Add bookings
Soylf/java-shareit pull request #2
Opened 2024-02-17 18:12 UTC by Soylf

2024-02-19 09:57 UTC, vlad-iv commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:6541/shareit
ожидается что бд на порту 6541
на этом порт обычное пробрасывают если запускают в докере через docker-compose (мы будем проходить в 16 спринте)
предлагаю указать тот порт, на котором БД

2024-02-20 16:16 UTC, Soylf commented
Я не понимаю, в чем у меня ошибка, укажите на ошибку вроде в репозиториях, но они работают исправно

2024-02-21 05:35 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +        status VARCHAR(10)
Бронирование не может быть без статуса (всегда есть какой-то). Поэтому добавить NOT NULL

2024-02-21 05:38 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
Все классы разложил по пакетам, контроллер тоже положи), например в пакет controller.

2024-02-21 05:40 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                       @RequestParam(required = false, defaultValue = "ALL") String state) {
required = false и наличие defaultValue противоречит друг другу, какое-то значение будет у параметра всегда

2024-02-21 06:18 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +        return BookingDto.builder().id(booking.getId()).start(booking.getStart()).end(booking.getEnd()).item(booking.getItem()).booker(booking.getBooker()).status(booking.getBookingStatus()).build();
Трудно читать код когда в строку вытянуто. Предпочтительней след. стиль

```
BookingDto.builder()
    .id(booking.getId())
    .start(booking.getStart())
    .end(booking.getEnd())
    .item(booking.getItem())
    .booker(booking.getBooker())
   .status(booking.getBookingStatus())
   .build();

```

2024-02-21 06:20 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/server/BookingService.java
> +
Лишние пустые строки убрать

2024-02-21 06:22 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/server/BookingServiceImpl.java
> +        if (bookingRequestDto.getStart().isAfter(bookingRequestDto.getEnd())
Проверку входных параметров принято размещать в самом верху метода недалеко от сигнатуры метода. Так проще потом будет читать код.

2024-02-21 06:34 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/server/BookingServiceImpl.java
> +            case "ALL":
Лучше сделать перечислимое чем использовать строки

2024-02-21 06:36 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/error/exception/BadConflictException.java
> +public class BadConflictException extends RuntimeException {
Плохое название класса) ПлохойКонфликт - конфликт не может быть хорошим по определению.
Можно просто ConflictException

2024-02-21 06:43 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/error/RestExceptionHandler.java
> +
Нужно еще добавить 
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.BAD_REQUEST)
	public ErrorResponse handleThrowable(final ValidationException e) 
        ...
```
Он будет перехватывать ошибкт валидации Dto с аннотациями

2024-02-21 06:43 UTC, VadimZharkov requested changes
Можно улучшить

2024-02-21 16:08 UTC, VadimZharkov approved these changes

2024-02-21 17:04 UTC, closed without merging